### ISSUE TITLE
Make the App Responsive

### ISSUE THREAD

**Issue by MarcoMorawec** [Ellcat/ouch-and-tods#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Ellcat** [comment]
Add  this to the  head>  
meta name="viewport" content="width=device-width, initial-scale=1">'

**Comment by MarcoMorawec** [comment]
@Ellcat :+1: 

Make sure you close the issue now that you solved it :)
